[build]
  base    = "frontend"
  command = "npm ci && SKIP_PREFLIGHT_CHECK=true npm run build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  CI = "false"
  SKIP_PREFLIGHT_CHECK = "true"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
